<a href="https://colab.research.google.com/github/Rishu-N/TENSORFLOW/blob/main/NLP_LIKED_NOTLIKED.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import nltk
import re

nltk.download("stopwords")
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


# TEXT PROCESSING

In [2]:
a = "Hii all!!!, I'am Rishu Nand. Welcome to AI Session"
a

"Hii all!!!, I'am Rishu Nand. Welcome to AI Session"

In [3]:
# STEP 1 : Remove special characters with regex. (re)

reg = re.sub('[^a-zA-Z]',' ',a)  # ^ == NOT/NEGATION
reg

'Hii all     I am Rishu Nand  Welcome to AI Session'

In [4]:
# STEP 2 : Convert uppercase letters to lowercase

lw = reg.lower()
lw

'hii all     i am rishu nand  welcome to ai session'

In [5]:
# STEP 3 : Split the input

wd  = lw.split()
wd

['hii', 'all', 'i', 'am', 'rishu', 'nand', 'welcome', 'to', 'ai', 'session']

In [6]:
print(stopwords.words("english"))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [7]:
print(stopwords.words("chinese"))

['一', '一下', '一些', '一切', '一则', '一天', '一定', '一方面', '一旦', '一时', '一来', '一样', '一次', '一片', '一直', '一致', '一般', '一起', '一边', '一面', '万一', '上下', '上升', '上去', '上来', '上述', '上面', '下列', '下去', '下来', '下面', '不一', '不久', '不仅', '不会', '不但', '不光', '不单', '不变', '不只', '不可', '不同', '不够', '不如', '不得', '不怕', '不惟', '不成', '不拘', '不敢', '不断', '不是', '不比', '不然', '不特', '不独', '不管', '不能', '不要', '不论', '不足', '不过', '不问', '与', '与其', '与否', '与此同时', '专门', '且', '两者', '严格', '严重', '个', '个人', '个别', '中小', '中间', '丰富', '临', '为', '为主', '为了', '为什么', '为什麽', '为何', '为着', '主张', '主要', '举行', '乃', '乃至', '么', '之', '之一', '之前', '之后', '之後', '之所以', '之类', '乌乎', '乎', '乘', '也', '也好', '也是', '也罢', '了', '了解', '争取', '于', '于是', '于是乎', '云云', '互相', '产生', '人们', '人家', '什么', '什么样', '什麽', '今后', '今天', '今年', '今後', '仍然', '从', '从事', '从而', '他', '他人', '他们', '他的', '代替', '以', '以上', '以下', '以为', '以便', '以免', '以前', '以及', '以后', '以外', '以後', '以来', '以至', '以至于', '以致', '们', '任', '任何', '任凭', '任务', '企图', '伟大', '似乎', '似的', '但', '但是', '何', '何况', '何处', '何时', '作为', '你', '你们', '你的', '使得', '使用'

In [8]:
print(stopwords.words("french"))

['au', 'aux', 'avec', 'ce', 'ces', 'dans', 'de', 'des', 'du', 'elle', 'en', 'et', 'eux', 'il', 'ils', 'je', 'la', 'le', 'les', 'leur', 'lui', 'ma', 'mais', 'me', 'même', 'mes', 'moi', 'mon', 'ne', 'nos', 'notre', 'nous', 'on', 'ou', 'par', 'pas', 'pour', 'qu', 'que', 'qui', 'sa', 'se', 'ses', 'son', 'sur', 'ta', 'te', 'tes', 'toi', 'ton', 'tu', 'un', 'une', 'vos', 'votre', 'vous', 'c', 'd', 'j', 'l', 'à', 'm', 'n', 's', 't', 'y', 'été', 'étée', 'étées', 'étés', 'étant', 'étante', 'étants', 'étantes', 'suis', 'es', 'est', 'sommes', 'êtes', 'sont', 'serai', 'seras', 'sera', 'serons', 'serez', 'seront', 'serais', 'serait', 'serions', 'seriez', 'seraient', 'étais', 'était', 'étions', 'étiez', 'étaient', 'fus', 'fut', 'fûmes', 'fûtes', 'furent', 'sois', 'soit', 'soyons', 'soyez', 'soient', 'fusse', 'fusses', 'fût', 'fussions', 'fussiez', 'fussent', 'ayant', 'ayante', 'ayantes', 'ayants', 'eu', 'eue', 'eues', 'eus', 'ai', 'as', 'avons', 'avez', 'ont', 'aurai', 'auras', 'aura', 'aurons', 'aur

In [9]:
# STEP 4 : Removing stopwords
  # list comprehension
  # syntax:  [Expression/output for iteration in variable]

sw = [w for w in wd if w not in set(stopwords.words("english"))]
sw

['hii', 'rishu', 'nand', 'welcome', 'ai', 'session']

In [10]:
# STEP 5 : Stemming on data
  #LAMENTIZATION - Meaningful words
  #Stametization - Meaningless words (shortform of original value)

ps = PorterStemmer()

In [11]:
p = [ps.stem(w) for w in sw ]
p

['hii', 'rishu', 'nand', 'welcom', 'ai', 'session']

In [12]:
# STEP 6 : Joining the words

st = ' '.join(p)
st

'hii rishu nand welcom ai session'

In [13]:
# STEP 7: Convert text to numerical format

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

cv.fit_transform([st]).toarray()

array([[1, 1, 1, 1, 1, 1]])

# WITH DATASET

In [14]:
df = pd.read_csv("/content/Restaurant_Reviews.tsv", delimiter = '\t')
df.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [15]:
df.shape

(1000, 2)

In [16]:
data = [] # list
for i in range(1000):
  review = df.Review[i]
  review = re.sub('[^a-zA-Z]',' ',review) #removing special characters
  review = review.lower()
  review = review.split()
  review = [ps.stem(w) for w in review if w not in set(stopwords.words('english'))]
  review = ' '.join(review)
  data.append(review) #for saving the iteration(preprocess data)

data

['wow love place',
 'crust good',
 'tasti textur nasti',
 'stop late may bank holiday rick steve recommend love',
 'select menu great price',
 'get angri want damn pho',
 'honeslti tast fresh',
 'potato like rubber could tell made ahead time kept warmer',
 'fri great',
 'great touch',
 'servic prompt',
 'would go back',
 'cashier care ever say still end wayyy overpr',
 'tri cape cod ravoli chicken cranberri mmmm',
 'disgust pretti sure human hair',
 'shock sign indic cash',
 'highli recommend',
 'waitress littl slow servic',
 'place worth time let alon vega',
 'like',
 'burritto blah',
 'food amaz',
 'servic also cute',
 'could care less interior beauti',
 'perform',
 'right red velvet cake ohhh stuff good',
 'never brought salad ask',
 'hole wall great mexican street taco friendli staff',
 'took hour get food tabl restaur food luke warm sever run around like total overwhelm',
 'worst salmon sashimi',
 'also combo like burger fri beer decent deal',
 'like final blow',
 'found place acc

In [17]:
# convert to numerical

x = cv.fit_transform(data).toarray()
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [18]:
y = df.Liked.values
y

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,

In [19]:
# SPLITTING DATA

from sklearn.model_selection import train_test_split
X_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=42)

## MODEL BUILDING

### NAIVE BAYES

In [20]:
from sklearn.naive_bayes import BernoulliNB
model = BernoulliNB()

In [21]:
model.fit(X_train,y_train)

BernoulliNB()

In [22]:
y_pred = model.predict(x_test)
y_pred

array([0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1])

In [23]:
from sklearn.metrics import accuracy_score

score = accuracy_score(y_test,y_pred)
score

0.7533333333333333

In [24]:
pd.crosstab(y_test,y_pred)

col_0    0    1
row_0          
0      110   42
1       32  116

In [25]:
import pickle
pickle.dump(model, open("review.pkl",'wb'))

### ANN MODEL

In [26]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [27]:
model1 = Sequential()
model1.add(Dense(1500,activation = "relu"))
model1.add(Dense(3000,activation = "relu"))
model1.add(Dense(1,activation = "sigmoid"))

In [28]:
model1.compile(optimizer = "adam", loss="binary_crossentropy",metrics=["accuracy"])

In [30]:
model1.fit(x,y, epochs = 25)

Epoch 1/25
32/32 [==============================] - 6s 5ms/step - loss: 0.6244 - accuracy: 0.6360
Epoch 2/25
32/32 [==============================] - 0s 4ms/step - loss: 0.1699 - accuracy: 0.9350
Epoch 3/25
32/32 [==============================] - 0s 4ms/step - loss: 0.0451 - accuracy: 0.9810
Epoch 4/25
32/32 [==============================] - 0s 5ms/step - loss: 0.0233 - accuracy: 0.9950
Epoch 5/25
32/32 [==============================] - 0s 5ms/step - loss: 0.0141 - accuracy: 0.9960
Epoch 6/25
32/32 [==============================] - 0s 5ms/step - loss: 0.0146 - accuracy: 0.9940
Epoch 7/25
32/32 [==============================] - 0s 4ms/step - loss: 0.0136 - accuracy: 0.9960
Epoch 8/25
32/32 [==============================] - 0s 5ms/step - loss: 0.0124 - accuracy: 0.9970
Epoch 9/25
32/32 [==============================] - 0s 5ms/step - loss: 0.0126 - accuracy: 0.9930
Epoch 10/25
32/32 [==============================] - 0s 5ms/step - loss: 0.0182 - accuracy: 0.9940
Epoch 11/25
32/32 [

In [31]:
model1.save("ann_review.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [33]:
model1.fit(X_train,y_train, epochs = 25,validation_data=(x_test,y_test))

Epoch 1/25
22/22 [==============================] - 0s 15ms/step - loss: 0.0044 - accuracy: 0.9971 - val_loss: 0.0159 - val_accuracy: 0.9933
Epoch 2/25
22/22 [==============================] - 0s 7ms/step - loss: 0.0026 - accuracy: 0.9986 - val_loss: 0.0254 - val_accuracy: 0.9867
Epoch 3/25
22/22 [==============================] - 0s 8ms/step - loss: 0.0012 - accuracy: 1.0000 - val_loss: 0.0320 - val_accuracy: 0.9867
Epoch 4/25
22/22 [==============================] - 0s 7ms/step - loss: 6.9512e-04 - accuracy: 1.0000 - val_loss: 0.0371 - val_accuracy: 0.9867
Epoch 5/25
22/22 [==============================] - 0s 9ms/step - loss: 4.8070e-04 - accuracy: 1.0000 - val_loss: 0.0416 - val_accuracy: 0.9867
Epoch 6/25
22/22 [==============================] - 0s 7ms/step - loss: 3.3838e-04 - accuracy: 1.0000 - val_loss: 0.0459 - val_accuracy: 0.9867
Epoch 7/25
22/22 [==============================] - 0s 6ms/step - loss: 2.6882e-04 - accuracy: 1.0000 - val_loss: 0.0492 - val_accuracy: 0.9867
Epo

## TESTING THE MODELS

In [46]:
def new_review(new_review):
  new_review = new_review
  new_review = re.sub('[^a-zA-Z]',' ',new_review)
  new_review = new_review.lower()
  new_review = new_review.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  new_review = [ps.stem(word) for word in new_review if not word in set (all_stopwords)]
  new_review = ' '.join(new_review)
  new_ = [new_review]
  new_X_test = cv.transform(new_).toarray()
  new_y_pred = model1.predict(new_X_test)
  if new_review[0] == 1:
    print("LIKE")
  else:
    print("NOT LIKED")
  return new_y_pred
new_review(str(input("Enter the review...")))


Enter the review...sleeping tonight
1/1 [==============================] - 0s 26ms/step
NOT LIKED


array([[0.00096372]], dtype=float32)

In [47]:
## Testing the model(Naive bayes)

def new_review(new_review):
  new_review = new_review
  new_review = re.sub('[^a-zA-Z]',' ',new_review)
  new_review = new_review.lower()
  new_review = new_review.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  new_review = [ps.stem(word) for word in new_review if not word in set (all_stopwords)]
  new_review = ' '.join(new_review)
  new_ = [new_review]
  new_X_test = cv.transform(new_).toarray()
  new_y_pred = model.predict(new_X_test)
  return new_y_pred
new_review = new_review(str(input("Enter the review...")))
if new_review[0]== 1:
  print("Liked")
else :
  print('Not liked')

Enter the review...wow i hate this place
Liked


In [48]:
## Testing the model(ANN)

def new_review(new_review):
  new_review = new_review
  new_review = re.sub('[^a-zA-Z]',' ',new_review)
  new_review = new_review.lower()
  new_review = new_review.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  new_review = [ps.stem(word) for word in new_review if not word in set (all_stopwords)]
  new_review = ' '.join(new_review)
  new_ = [new_review]
  new_X_test = cv.transform(new_).toarray()
  new_y_pred = model1.predict(new_X_test)
  return new_y_pred
new_review = new_review(str(input("Enter the review...")))
if new_review[0]== 1:
  print("Liked")
else :
  print('Not liked')

Enter the review...wow i hate this place
1/1 [==============================] - 0s 28ms/step
Not liked
